# Use an AWS-provided base image for your runtime (e.g., Python 3.8)
FROM public.ecr.aws/lambda/python:3.8

RUN mkdir ./tools
RUN mkdir ./image

# Copy function code and dependencies
COPY src/daily_report/app.py ./
COPY src/daily_report/requirements.txt ./
COPY tools/ ./tools
COPY src/daily_report/image/ ./image

# Install dependencies
RUN pip install -r requirements.txt

# Set the CMD to your handler
CMD ["app.lambda_handler"]
