AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application to generate PDF reports and send via email.

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true

  MyUsagePlan:
    Type: "AWS::ApiGateway::UsagePlan"
    Properties:
      ApiStages:
        - ApiId:
            Ref: "MyApi"
          Stage: "Prod"
      Description: "A usage plan for important customers"
      Quota:
        Limit: 5000
        Offset: 0
        Period: "MONTH"
      Throttle:
        BurstLimit: 200
        RateLimit: 100

  MyApiKey:
    Type: "AWS::ApiGateway::ApiKey"
    Properties:
      Description: "My API Key"
      Enabled: true
      GenerateDistinctId: true
      Name: "MyAPIKey"
      StageKeys:
        - RestApiId:
            Ref: "MyApi"
          StageName: "Prod"

  GenerateReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: [ "app.lambda_handler" ]
      Timeout: 15
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: /report
            Method: post
            RestApiId:
              Ref: MyApi
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: "*"
        - Statement: # New policy statement to allow ssm:GetParameter action
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: arn:aws:ssm:us-east-1:047672427450:parameter/ALPHAVANTAGE_API_KEY
    Metadata:
      Dockerfile: Dockerfile.report
      DockerContext: .
      DockerTag: v1

  UsagePlanKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    Properties:
      KeyId:
        Ref: "MyApiKey"
      KeyType: "API_KEY"
      UsagePlanId:
        Ref: "MyUsagePlan"

Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod stage"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/report"
